#!/usr/bin/env bash
# writes "I am alive" to the file /tmp/my_proces indefinitely
# wait time of  two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
